package com.reburp.routes

import burp.api.montoya.MontoyaApi
import burp.api.montoya.bambda.BambdaImportResult
import com.reburp.*
import io.ktor.http.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*

fun Routing.bambdaRoutes(api: MontoyaApi) {

    /**
     * Import a raw Bambda script into the Burp Bambda library.
     * The script must be valid Java compatible with the Burp custom action API.
     * Once imported, load it from the Bambda library in the Repeater Custom actions side panel.
     */
    post("/api/bambda/import") {
        val req = runCatching { call.receive<BambdaImportRequest>() }.getOrElse {
            return@post call.respond(HttpStatusCode.BadRequest, ErrorResponse(it.message ?: "Invalid request body"))
        }
        val source = wrapBambdaSource(req.name, req.source)
        val result = runCatching { api.bambda().importBambda(source) }.getOrElse {
            return@post call.respond(HttpStatusCode.InternalServerError, ErrorResponse("importBambda failed: ${it.message}"))
        }
        val errors = result.importErrors() ?: emptyList()
        val status = when (result.status()) {
            BambdaImportResult.Status.LOADED_WITHOUT_ERRORS -> "imported"
            BambdaImportResult.Status.LOADED_WITH_ERRORS -> "imported_with_errors"
            else -> "failed"
        }
        call.respond(BambdaImportResponse(status = status, errors = errors))
    }

    /**
     * Generate a multi-step chain Bambda from a list of steps, import it into the Bambda library,
     * and return the generated source. Each step can extract values from the response and inject
     * them into subsequent requests. Enable auto-run in Repeater to execute the full chain.
     *
     * Steps support:
     * - extract: jsonpath keys like "$.access" or regex patterns like "sessionid=([^;]+)"
     * - inject: variable -> header string template, e.g. {"token": "Authorization: Bearer {{token}}"}
     */
    post("/api/bambda/generate-chain") {
        val req = runCatching { call.receive<GenerateChainRequest>() }.getOrElse {
            return@post call.respond(HttpStatusCode.BadRequest, ErrorResponse(it.message ?: "Invalid request body"))
        }
        if (req.steps.isEmpty()) {
            return@post call.respond(HttpStatusCode.BadRequest, ErrorResponse("At least one step is required"))
        }
        val source = generateChainBambda(req)
        val wrapped = wrapBambdaSource(req.name, source)
        val result = runCatching { api.bambda().importBambda(wrapped) }.getOrElse {
            return@post call.respond(
                GenerateChainResponse(name = req.name, source = wrapped, imported = false,
                    import_errors = listOf("importBambda failed: ${it.message}"))
            )
        }
        val errors = result.importErrors() ?: emptyList()
        val imported = result.status() != null
        call.respond(GenerateChainResponse(name = req.name, source = wrapped, imported = imported, import_errors = errors))
    }
}

// Wraps bare source in the .bambda envelope format Burp expects
private fun wrapBambdaSource(name: String, source: String): String {
    // Deterministic UUID from name so re-importing the same named Bambda overwrites in place
    val safeId = java.util.UUID.nameUUIDFromBytes(name.toByteArray()).toString()
    val safeName = name.replace("\"", "'")
    return """
id: $safeId
name: "$safeName"
function: CUSTOM_ACTION
location: REPEATER
source: |
${source.trimEnd().lines().joinToString("\n") { "  $it" }}
""".trimStart()
}

// Generates a Java Bambda script for a multi-step HTTP chain
private fun generateChainBambda(req: GenerateChainRequest): String {
    val sb = StringBuilder()
    sb.appendLine("/**")
    sb.appendLine(" * Chain: ${req.name}")
    sb.appendLine(" * Auto-generated by reburp - ${req.steps.size} step(s)")
    sb.appendLine(" * Enable auto-run to execute on every send, or click Run manually.")
    sb.appendLine(" */")
    sb.appendLine("var vars = new java.util.HashMap<String, String>();")
    sb.appendLine()

    req.steps.forEachIndexed { i, step ->
        val stepNum = i + 1
        val totalSteps = req.steps.size
        sb.appendLine("// ── Step $stepNum/$totalSteps: ${step.method} ${step.path} ──")
        sb.appendLine("var req$stepNum = api().http().createRequest(\"${req.host}\", ${req.port}, ${req.https});")
        sb.appendLine("req$stepNum = req$stepNum.withMethod(\"${step.method}\").withPath(\"${step.path.replace("\"", "\\\"")}\");")

        // Inject extracted variables from previous steps
        step.inject.forEach { (varName, headerTemplate) ->
            val header = headerTemplate.replace("{{$varName}}", "\").concat(vars.getOrDefault(\"$varName\", \"\")).concat(\"")
            val parts = headerTemplate.split(":", limit = 2)
            if (parts.size == 2) {
                val hName = parts[0].trim()
                val hVal = parts[1].trim().replace("{{$varName}}", "\").concat(vars.getOrDefault(\"$varName\", \"\")).concat(\"")
                sb.appendLine("req$stepNum = req$stepNum.withAddedHeader(\"$hName\", \"$hVal\");")
            }
        }

        // Static headers
        step.headers.forEach { (k, v) ->
            sb.appendLine("req$stepNum = req$stepNum.withAddedHeader(\"$k\", \"${v.replace("\"", "\\\"")}\");")
        }

        // Body
        if (!step.body.isNullOrBlank()) {
            sb.appendLine("req$stepNum = req$stepNum.withBody(\"${step.body.replace("\"", "\\\"")}\");")
        }

        sb.appendLine("var rr$stepNum = api().http().sendRequest(req$stepNum);")
        sb.appendLine("logging().logToOutput(\"[Step $stepNum/$totalSteps] ${step.method} ${step.path} -> \" + rr$stepNum.response().statusCode());")

        // Extract values for next steps
        step.extract.forEach { (varName, pattern) ->
            if (pattern.startsWith("$.")) {
                // Simple jsonpath-like key extraction (first-level only without external lib)
                val key = pattern.removePrefix("$.")
                sb.appendLine("var body$stepNum = rr$stepNum.response().bodyToString();")
                sb.appendLine("var match$stepNum$varName = body$stepNum.replaceAll(\".*\\\\\"$key\\\\\":\\\\s*\\\\\"([^\\\"]+)\\\\\".*\", \"\$1\");")
                sb.appendLine("if (!match$stepNum$varName.equals(body$stepNum)) { vars.put(\"$varName\", match$stepNum$varName); logging().logToOutput(\"  extracted $varName=\" + match$stepNum$varName); }")
            } else {
                // Regex extraction
                val safePattern = pattern.replace("\\", "\\\\").replace("\"", "\\\"")
                sb.appendLine("var body$stepNum = rr$stepNum.response().bodyToString();")
                sb.appendLine("var m$stepNum$varName = java.util.regex.Pattern.compile(\"$safePattern\").matcher(body$stepNum);")
                sb.appendLine("if (m$stepNum$varName.find()) { vars.put(\"$varName\", m$stepNum$varName.group(1)); logging().logToOutput(\"  extracted $varName=\" + m$stepNum$varName.group(1)); }")
            }
        }
        sb.appendLine()
    }

    sb.appendLine("logging().logToOutput(\"Chain complete: ${req.name}\");")
    return sb.toString()
}
